name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  ZK_NOTEBOOK_DIR: "./src/tests/notebook"
  DATABASE_URL: "file:./dev.db"
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: pnpm test
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run unit tests
        run: pnpm test:int
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Install playwright
        run: pnpm playwright install
      - name: Run unit tests
        run: pnpm test:e2e
